version: "2"

run:
  timeout: 10m
  tests: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(gitlab.com/crusoeenergy)
    goimports:
      local-prefixes:
        - gitlab.com/crusoeenergy
    golines:
      max-len: 120 # trims lines automatically but some things like long strings don't.
      reformat-tags: false # superseded by tagalign

linters:
  default: all

  disable:
    # intentionally disabled due to disagreement
    - depguard    # explicitly declaring our tree of dependencies is low value
    - exhaustruct # golang structs should have reasonable zero values
    - ireturn     # it's okay to use abstractions
    - nilnil      # we're fine returning nil for the caller to check a non failed no value.
    - noinlineerr # inline errors are not a hill to die on
    - mnd         # too many cases of obvious values that don't need noisy var declarations

    # already covered by revive
    - cyclop
    - forcetypeassert
    - funlen
    - gocognit
    - lll

    # replaced by wsl_v5
    - wsl

    # replaced by paralleltest
    - tparallel

    # temporarily disabled until we have bandwidth to address lint failures
    - err113

  settings:

    gosec:
      excludes:
        - "G304"
        - "G703"

    revive:
      enable-all-rules: true

      rules:
        - name: add-constant
          disabled: true

        # This conflicts with nonamedreturns, which aligns more with our style.
        - name: confusing-results
          disabled: true

        # The default is 7, to allow for some of go's oddities, bump to 10.
        # We can easily get simple yet a high complexity with channels and error handling.
        - name: cognitive-complexity
          arguments: [10]

        # The exhaustive linter checks that we use all values, so requiring a default is redundant.
        - name: enforce-switch-style
          arguments: [allowNoDefault]

        - name: function-length
          arguments: [60, 0]

        # Allow for long strings, others will be trimmed by golines.
        - name: line-length-limit
          arguments:
            - 240

        # Requiring comments for every package is going to drive developers crazy.
        - name: package-comments
          disabled: true

        - name: unhandled-error
          arguments:
            - "strings.Builder.WriteString" # This never returns an error.
            - "^fmt.Fprint\\w*" # Most buffers we use don't error, and even if it did most people don't care to handle it...

    varnamelen:
      ignore-decls:
        - i int                       # universal value for an int
        - sb strings.Builder          # common abbreviation for strings.Builder
        - sb *strings.Builder

