version: 2
builds:
  - id: tfsortplus
    main: ./main.go
    binary: tfsortplus
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X github.com/thespags/tfsortplus/cmd.version={{.Version}} -X github.com/thespags/tfsortplus/cmd.commit={{.Commit}} -X github.com/thespags/tfsortplus/cmd.date={{.Date}}
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
